server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_board
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      profile: dev
      name: config
  sql:
    init:
      mode: embedded
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
