server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      profile: dev
      name: config
